version: "2.2"

services:
  master:
    build: 
      context: ./
      dockerfile: ./master/Dockerfile
      args:
        - PORT_UVICORN=$PORT_UVICORN_MASTER
    environment:
      - SECONDARY_INFO=$SECONDARY_INFO
    ports: 
      - $PORT_UVICORN_MASTER:$PORT_UVICORN_MASTER
    networks:
      - deploy_network1
      - deploy_network2
    restart: on-failure
    container_name: master

  secondary1:
    build:
      context: ./
      dockerfile: ./secondary/Dockerfile
      args:
        - PORT_UVICORN=$PORT_UVICORN_SECONDARY1
    environment:
      - PORT=$PORT_SECONDARY1
    ports: 
      - $PORT_UVICORN_SECONDARY1:$PORT_UVICORN_SECONDARY1
    depends_on: 
      - master
    links:
      - master
    networks:
      - deploy_network1
    restart: on-failure
    container_name: secondary1

  secondary2:
    build:
      context: ./
      dockerfile: ./secondary/Dockerfile
      args:
        - PORT_UVICORN=$PORT_UVICORN_SECONDARY2
    environment:
      - PORT=$PORT_SECONDARY2
    ports: 
      - $PORT_UVICORN_SECONDARY2:$PORT_UVICORN_SECONDARY2
    depends_on: 
      - master
    links:
      - master
    networks:
      - deploy_network2
    restart: on-failure
    container_name: secondary2

networks:
  deploy_network1:
    driver: bridge
  deploy_network2:
    driver: bridge